input {
  beats {
    port => 5044
  }
}

filter {
  if [message] {
    json {
      source => "message"
      target => "log"                 
      skip_on_invalid_json => true   
    }
  }

  if [log][asctime] {
    date {
      match => ["[log][asctime]", "yyyy-MM-dd HH:mm:ss,SSS"]
      target => "@timestamp"
      timezone => "UTC+1"
    }
  }

  if [log][levelname] {
    mutate {
      rename => { "[log][levelname]" => "log_level" }
      lowercase => ["log_level"]
    }
  }

  if [log][message] {
    mutate {
      rename => { "[log][message]" => "message" }
    }
  }

  if [log][name] {
    mutate {
      rename => { "[log][name]" => "logger_name" }
    }
  }

  mutate {
    remove_field => ["log"]  
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "reasona-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
