dataset:
  name: codelion/synth-1B
  source: huggingface

columns:
  text:
    type: string
    role: content
    
  synth_id:
    type: string
    role: id

  language:
    type: string
    role: metadata

  exercise:
    type: string
    role: metadata

target:
  name: text

indexing:
  text_fields:
    - text

  metadata_fields:
    - synth_id
    - language
    - exercise
