dataset:
  name: wikimedia/wikipedia
  source: huggingface
  config: 20231101.en

columns:
  id:
    type: string
    role: id

  url:
    type: string
    role: metadata

  title:
    type: string
    role: metadata

  text:
    type: string
    role: content

target:
  name: text

indexing:
  text_fields:
    - text

  metadata_fields:
    - id
    - title
    - url
