filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /app/logs/**/*.log
      - /app/logs/**/*.json
    scan_frequency: 5s
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: message

output.logstash:
  hosts: ["logstash:5044"]
